### ISSUE TITLE
It only allows async functions

### ISSUE THREAD

**Issue by PabloSzx** [mcollina/single-user-cache#1]
While using [mercurius-loaders](https://mercurius.dev/#/docs/loaders) I encountered the problem that ".then" is hardcoded, which means that if the function doesn't return a promise, it just throws.

![image](https://user-images.githubusercontent.com/8672915/99137672-29a35d80-260b-11eb-8fe5-02a8780681c9.png)

**Comment by mcollina** [comment]
What's your use case?

The DataLoader pattern is useful for batching asynchronous operation together.. why use a synchronous batching API? We should likely provide a better error for this.

**Comment by PabloSzx** [comment]
I think it's not so much about a specific use case, usually if the possible promises would be used through await and the returning value is not a actually promise it wouldn't matter and it goes through, but if using await has some performance penalties (I'm not sure about that) then it would be better to leave it as it is.

**Comment by mcollina** [comment]
`await` is a bit slower than `then`. Maybe we could implement the same functionality?
